// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IsMU2Wt0vfs4Ba61OUidehP8xPwOHWo',
    appId: '1:463456068964:web:08584a26e3e7f212584671',
    messagingSenderId: '463456068964',
    projectId: 'upaychat-e53e2',
    authDomain: 'upaychat-e53e2.firebaseapp.com',
    databaseURL: 'https://upaychat-e53e2-default-rtdb.firebaseio.com',
    storageBucket: 'upaychat-e53e2.appspot.com',
    measurementId: 'G-25916DW2MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8IsMU2Wt0vfs4Ba61OUidehP8xPwOHWo',
    appId: '1:463456068964:android:f53bb6b5a01e78ac584671',
    messagingSenderId: '463456068964',
    projectId: 'upaychat-e53e2',
    databaseURL: 'https://upaychat-e53e2-default-rtdb.firebaseio.com',
    storageBucket: 'upaychat-e53e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6S0oyPczZdrq-aqouPNyRbWgLIoKnAnE',
    appId: '1:463456068964:ios:cad59ba25fc49e0d584671',
    messagingSenderId: '463456068964',
    projectId: 'upaychat-e53e2',
    databaseURL: 'https://upaychat-e53e2-default-rtdb.firebaseio.com',
    storageBucket: 'upaychat-e53e2.appspot.com',
    androidClientId: '463456068964-294rblik2feu6dr344i29hodpeig6l70.apps.googleusercontent.com',
    iosClientId: '463456068964-dh2oof9cu47ktaf0frnbhu9pn188ufa4.apps.googleusercontent.com',
    iosBundleId: 'com.upaychat.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6S0oyPczZdrq-aqouPNyRbWgLIoKnAnE',
    appId: '1:463456068964:ios:cad59ba25fc49e0d584671',
    messagingSenderId: '463456068964',
    projectId: 'upaychat-e53e2',
    databaseURL: 'https://upaychat-e53e2-default-rtdb.firebaseio.com',
    storageBucket: 'upaychat-e53e2.appspot.com',
    androidClientId: '463456068964-294rblik2feu6dr344i29hodpeig6l70.apps.googleusercontent.com',
    iosClientId: '463456068964-dh2oof9cu47ktaf0frnbhu9pn188ufa4.apps.googleusercontent.com',
    iosBundleId: 'com.upaychat.finance',
  );
}
